@urlServer = http://localhost:8080/investments

##---- INVESTMENT ----##

### POST
POST {{urlServer}}/user/d56c2b5c-aba1-4efa-acc3-e402a6d17dc4
Content-Type: application/json

{
  "type": 1,
  "quantity": 0,
  "symbol": "ITUB4",
  "purchasePrice": 47.45,
  "purchaseDateTime": "2026-02-23T00:34:00"
}

###

### FIND BY USER ID
GET {{urlServer}}/user/d56c2b5c-aba1-4efa-acc3-e402a6d17dc4

###

### FIND BY TYPE ID
GET {{urlServer}}/user/d56c2b5c-aba1-4efa-acc3-e402a6d17dc4/type/3

###

### SUMMARY
GET {{urlServer}}/summary/d56c2b5c-aba1-4efa-acc3-e402a6d17dc4

###

### UPDATE
PUT {{urlServer}}
Content-Type: application/json

{
  "id": "814a3037-4088-468d-bb3a-5728978716b2",
  "type": 2,
  "quantity": 110,
  "symbol": "ASTER",
  "purchasePrice": 0.720,
  "purchaseDateTime": "2025-02-20T10:05:12"
}

###

### DELETE
DELETE {{urlServer}}
Content-Type: application/json

{
  "id": "0c6d54a6-fc61-4af5-9155-591e6c8916a3"
}